apiVersion: apps/v1
kind: Deployment
metadata:
  name: ableton-ebs
  labels:
    app: ableton-ebs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ableton-ebs
  template:
    metadata:
      labels:
        app: ableton-ebs
    spec:
      containers:
      - name: ebs
        image: ghcr.io/fabian-lindhardt/ableton-ebs:latest 
        # Note: You need to build and push this image, or change the image name
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        # Secrets should ideally be mounted from a k8s Secret, but for simplicity here:
        - name: TWITCH_CLIENT_ID
          value: "61aryh4yx4v94a1309tk5dqz8kyrvp"
        - name: TWITCH_SECRET
          valueFrom:
            secretKeyRef:
              name: ableton-ebs-secrets
              key: TWITCH_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: ableton-ebs
spec:
  selector:
    app: ableton-ebs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Secret
metadata:
  name: ableton-ebs-secrets
type: Opaque
stringData:
  TWITCH_SECRET: "L0KsD31sIuMSFCcPtQOpC2kN6YBlXXwl/iyV+o3+JxQ="
  TWITCH_CLIENT_SECRET: "xus0zndfmvlhrlqzeazyxm55oi1ft0"
