apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: audio-signaling
  namespace: audio-signaling
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
    - hosts:
        - vdo.flairtec.de
      secretName: vdo-ninja-tls
  rules:
    - host: vdo.flairtec.de
      http:
        paths:
          # Audio Signaling WebSocket
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: audio-signaling
                port:
                  number: 3000
