apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vdo-ninja
  namespace: vdo-ninja
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
    - hosts:
        - vdo.flairtec.de
      secretName: vdo-ninja-tls
  rules:
    - host: vdo.flairtec.de
      http:
        paths:
          # Frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vdo-ninja-frontend
                port:
                  number: 80
          # Signaling (Raw Websocket)
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: vdo-ninja-signaling
                port:
                  number: 3000
          # Legacy Signaling (Socket.io - deprecated)
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: vdo-ninja-signaling
                port:
                  number: 3000
