apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vdo-ninja
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
    - hosts:
        - vdo.example.com  # REPLACE with your domain
      secretName: vdo-ninja-tls
  rules:
    - host: vdo.example.com  # REPLACE with your domain
      http:
        paths:
          # Frontend
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vdo-ninja
                port:
                  number: 80
          # Signaling (Websocket)
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: vdo-ninja
                port:
                  number: 3000
